#!/bin/bash

# WooPreProduct Zip Script
# 
# Creates a clean zip archive of the project excluding development files,
# git files, vendor dependencies, and other unnecessary files.

echo "Creating preproduct.zip in /Users/oli/Mac/Apps/woo-package/ folder..."
zip -r ../woo-package/preproduct.zip . -x "*.DS_Store" "__MACOSX" "*.git*" "vendor/*" "node_modules/*" "tests/*" "test"
echo "Zip archive created successfully in /Users/oli/Mac/Apps/woo-package/ folder!" 